spring:
  application:
    name: notification-service
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: storex-notification
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

logging:
  level:
    com.notificationservice: INFO
    org.springframework.kafka: INFO
